### PR TITLE
Feat/login auth

### PR DESCRIPTION
**Pull request by austinwo**
- load controller and factory dependencies on index.html
- angular factory to handle user auth (log-in)
- angular controller to handle user input for log-in

### CODE REVIEW

**Comment by adlaika** [comment]
Looks good. Is the post request content the entire user object, or just username / password?

**Comment by adlaika** [comment]
oops. merged.

**Comment by adlaika** [comment]
also: does this close #23?

**Comment by austinwo** [comment]
the post request is sending the whole object, which contains user.username and user.password, this is for loggin in only, not signing up.

in view-login.html youll see that we attach the username and password properties on login.user.

And yes, this already includes the #23 we forgot to close #23. We'll change #23 to something else that we'll work on.

**Comment by adlaika** [comment]
I'm confused -- how are you going to get fields other than username and password out of a login page? Or will the rest of the object's fields just be empty?

**Comment by austinwo** [comment]
There aren't other properties other than username and password on the json object that's being attached wit the POST request to /login. 

What fields are you referring to?

POST request for /signup have additional properties.

But we only need username and password for POST for /login.

**Pull request merged**
